### ISSUE TITLE
webpack warnings in terminal

### ISSUE THREAD

**Issue by tomwayson** [tomwayson/esri-react-router-example#3]
I see these warnings:
```bash
WARNING in ./~/esri-loader/dist/index.js.map
Module parse failed: /Users/tom6947/code/esri-react-router-example/node_modules/esri-loader/dist/index.js.map Unexpected token (1:10)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:10)
    at Parser.pp$4.raise (/Users/tom6947/code/esri-react-router-example/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/tom6947/code/esri-react-router-example/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/Users/tom6947/code/esri-react-router-example/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/Users/tom6947/code/esri-react-router-example/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/Users/tom6947/code/esri-react-router-example/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseBlock (/Users/tom6947/code/esri-react-router-example/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$1.parseStatement (/Users/tom6947/code/esri-react-router-example/node_modules/acorn/dist/acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (/Users/tom6947/code/esri-react-router-example/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Users/tom6947/code/esri-react-router-example/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Users/tom6947/code/esri-react-router-example/node_modules/acorn/dist/acorn.js:3098:39)
 @ ./~/esri-loader/dist ^\.\/.*$

WARNING in ./~/esri-loader/dist/index.d.ts
Module parse failed: /Users/tom6947/code/esri-react-router-example/node_modules/esri-loader/dist/index.d.ts Unexpected token (1:7)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:7)
    at Parser.pp$4.raise (/Users/tom6947/code/esri-react-router-example/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/tom6947/code/esri-react-router-example/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.expect (/Users/tom6947/code/esri-react-router-example/node_modules/acorn/dist/acorn.js:597:28)
    at Parser.pp$1.parseExportSpecifiers (/Users/tom6947/code/esri-react-router-example/node_modules/acorn/dist/acorn.js:1215:10)
    at Parser.pp$1.parseExport (/Users/tom6947/code/esri-react-router-example/node_modules/acorn/dist/acorn.js:1186:30)
    at Parser.pp$1.parseStatement (/Users/tom6947/code/esri-react-router-example/node_modules/acorn/dist/acorn.js:719:71)
    at Parser.pp$1.parseTopLevel (/Users/tom6947/code/esri-react-router-example/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Users/tom6947/code/esri-react-router-example/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Users/tom6947/code/esri-react-router-example/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/Users/tom6947/code/esri-react-router-example/node_modules/webpack/lib/Parser.js:902:15)
 @ ./~/esri-loader/dist ^\.\/.*$
```

Why is webpack trying to parse those files?

**Comment by tomwayson** [comment]
I no longer see these after bumping to latest version of esri-loader.

resolved in d2abc46055495798d620052c32540eb933fdd85c
